# 2022 Predictions (2021 until more data for 22 available)

In this notebook I am going to use practice/qualifying data to predict F1 race results.  A priori I don't expect this to work very well.  In the first iteration I will just take all lap times from practice and qualifying to predict each car's mean race pace.  Some immediate problems that will limit the accuracy are


-  Practice session mayhem
    1.  All teams purposefully limit the cars performance, use unknown amounts of fuel, ...
    2.  Teams do different types of runs (race sim, quali sim, testing new parts...  and more...). In principle I could try and sort out quali sim laps and race sim laps manually or with k-means clustering.  
    3.  Different times of day for practice/race/qualy effect track temperatures
    
-  Mid season upgrades



The first implementation will be 1 neural network for each driver, that takes all the practice & quali lap times as input and predicts the race pace.  


First we set up the FastF1 library and data directory.

In [1]:
import fastf1 as ff1
from fastf1 import plotting
from matplotlib import pyplot as plt
import os

plotting.setup_mpl()

f1DataCache=os.path.join(os.path.expanduser('~'),'Documents','F1DataCache')
ff1.Cache.enable_cache(f1DataCache)

In [25]:
import logging
logger=logging.getLogger()
logger.setLevel(logging.WARNING)

In [26]:
ff1.get_event_schedule(2022).EventName

0      Pre-Season Track Session
1               Pre-Season Test
2            Bahrain Grand Prix
3      Saudi Arabian Grand Prix
4         Australian Grand Prix
5     Emilia Romagna Grand Prix
6              Miami Grand Prix
7            Spanish Grand Prix
8             Monaco Grand Prix
9         Azerbaijan Grand Prix
10          Canadian Grand Prix
11           British Grand Prix
12          Austrian Grand Prix
13            French Grand Prix
14         Hungarian Grand Prix
15           Belgian Grand Prix
16             Dutch Grand Prix
17           Italian Grand Prix
18         Singapore Grand Prix
19          Japanese Grand Prix
20     United States Grand Prix
21       Mexico City Grand Prix
22         São Paulo Grand Prix
23         Abu Dhabi Grand Prix
Name: EventName, dtype: object

In [27]:
weekend=ff1.get_event(2022, 'Bahrain')
fp1=weekend.get_practice(1)

In [32]:
fp1.load();

In [33]:
import pandas as pd

driverTLA = {}

for driver in fp1.drivers:
    TLA=ff1.api.driver_info(fp1.api_path)[driver]['Tla']
    driverTLA[driver]=TLA

In [35]:
fp1.weather_data

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:54.194000,20.1,36.0,1016.2,False,36.9,3,0.9
1,0 days 00:01:54.189000,20.2,36.0,1016.2,False,37.0,24,1.1
2,0 days 00:02:54.194000,20.0,37.0,1016.2,False,36.7,17,0.9
3,0 days 00:03:54.186000,19.9,37.0,1016.0,False,36.7,4,0.9
4,0 days 00:04:54.189000,19.9,37.0,1016.2,False,36.6,5,1.0
...,...,...,...,...,...,...,...,...
77,0 days 01:17:54.442000,19.6,36.0,1016.0,False,32.0,9,0.9
78,0 days 01:18:54.440000,19.7,36.0,1016.0,False,32.2,5,0.8
79,0 days 01:19:54.441000,19.6,36.0,1016.0,False,32.3,5,0.5
80,0 days 01:20:54.437000,19.6,35.0,1016.0,False,32.3,11,0.9
81,0 days 01:21:54.437000,19.6,36.0,1016.0,False,32.2,348,0.8

In [48]:
fp1.laps[fp1.laps['DriverNumber'].isin(['1'])]

,Time,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,...,SpeedST,Compound,TyreLife,FreshTyre,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
0,0 days 00:18:33.392000,1,NaT,1,1,NaT,NaT,NaT,NaT,NaT,...,193.0,NaN,NaN,NaN,NaT,Red Bull Racing,VER,1,False,NaT
1,0 days 00:20:19.908000,1,NaT,2,1,0 days 00:18:33.392000,NaT,NaT,0 days 00:00:46.433000,0 days 00:00:27.011000,...,NaN,HARD,2.0,True,0 days 00:18:33.392000,Red Bull Racing,VER,1,False,2022-03-18 12:03:33.405
2,0 days 00:21:57.674000,1,0 days 00:01:37.766000,3,1,NaT,NaT,0 days 00:00:30.695000,0 days 00:00:41.580000,0 days 00:00:25.491000,...,306.0,HARD,3.0,True,0 days 00:20:19.908000,Red Bull Racing,VER,2,True,2022-03-18 12:05:19.921
3,0 days 00:36:10.140000,1,NaT,4,2,NaT,0 days 00:24:20.357000,0 days 00:00:47.032000,NaT,NaT,...,190.0,HARD,1.0,True,0 days 00:21:57.674000,Red Bull Racing,VER,25,False,2022-03-18 12:06:57.687
4,0 days 00:38:04.834000,1,NaT,5,2,0 days 00:36:10.140000,NaT,NaT,0 days 00:00:45.882000,0 days 00:00:35.730000,...,NaN,MEDIUM,2.0,True,0 days 00:36:10.140000,Red Bull Racing,VER,1,False,2022-03-18 12:21:10.153
5,0 days 00:39:39.617000,1,0 days 00:01:34.783000,6,2,NaT,NaT,0 days 00:00:30.119000,0 days 00:00:40.789000,0 days 00:00:23.875000,...,309.0,MEDIUM,3.0,True,0 days 00:38:04.834000,Red Bull Racing,VER,1,True,2022-03-18 12:23:04.847
6,0 days 00:41:48.377000,1,0 days 00:02:08.760000,7,2,NaT,NaT,0 days 00:00:42.765000,0 days 00:01:00.164000,0 days 00:00:25.831000,...,288.0,MEDIUM,4.0,True,0 days 00:39:39.617000,Red Bull Racing,VER,1,True,2022-03-18 12:24:39.630
7,0 days 00:43:23.119000,1,0 days 00:01:34.742000,8,2,NaT,NaT,0 days 00:00:30.224000,0 days 00:00:40.815000,0 days 00:00:23.703000,...,310.0,MEDIUM,5.0,True,0 days 00:41:48.377000,Red Bull Racing,VER,1,True,2022-03-18 12:26:48.390
8,0 days 00:45:16.337000,1,0 days 00:01:53.218000,9,3,NaT,0 days 00:45:14.568000,0 days 00:00:34.951000,0 days 00:00:49.152000,0 days 00:00:29.115000,...,258.0,MEDIUM,1.0,True,0 days 00:43:23.119000,Red Bull Racing,VER,1,False,2022-03-18 12:28:23.132
9,0 days 00:56:26.499000,1,NaT,10,4,0 days 00:54:27.597000,0 days 00:56:24.693000,NaT,0 days 00:00:44.702000,0 days 00:00:28.840000,...,192.0,MEDIUM,6.0,False,0 days 00:45:16.337000,Red Bull Racing,VER,2,False,2022-03-18 12:30:16.350
10,0 days 00:58:37.303000,1,0 days 00:02:10.804000,11,4,0 days 00:56:46.437000,NaT,0 days 00:01:03.657000,0 days 00:00:42.700000,0 days 00:00:24.447000,...,199.0,MEDIUM,8.0,False,0 days 00:56:26.499000,Red Bull Racing,VER,2,False,2022-03-18 12:41:26.512
11,0 days 01:00:16.005000,1,0 days 00:01:38.702000,12,4,NaT,NaT,0 days 00:00:31.520000,0 days 00:00:42.499000,0 days 00:00:24.683000,...,291.0,MEDIUM,9.0,False,0 days 00:58:37.303000,Red Bull Racing,VER,1,True,2022-03-18 12:43:37.316
12,0 days 01:01:55.195000,1,0 days 00:01:39.190000,13,4,NaT,NaT,0 days 00:00:31.789000,0 days 00:00:42.890000,0 days 00:00:24.511000,...,285.0,MEDIUM,10.0,False,0 days 01:00:16.005000,Red Bull Racing,VER,1,True,2022-03-18 12:45:16.018
13,0 days 01:03:34.067000,1,0 days 00:01:38.872000,14,4,NaT,NaT,0 days 00:00:31.787000,0 days 00:00:42.524000,0 days 00:00:24.561000,...,282.0,MEDIUM,11.0,False,0 days 01:01:55.195000,Red Bull Racing,VER,1,True,2022-03-18 12:46:55.208
14,0 days 01:05:12.957000,1,0 days 00:01:38.890000,15,4,NaT,NaT,0 days 00:00:31.824000,0 days 00:00:42.433000,0 days 00:00:24.633000,...,284.0,MEDIUM,12.0,False,0 days 01:03:34.067000,Red Bull Racing,VER,1,True,2022-03-18 12:48:34.080
15,0 days 01:06:52.017000,1,0 days 00:01:39.060000,16,4,NaT,NaT,0 days 00:00:31.644000,0 days 00:00:42.611000,0 days 00:00:24.805000,...,289.0,MEDIUM,13.0,False,0 days 01:05:12.957000,Red Bull Racing,VER,1,True,2022-03-18 12:50:12.970
16,0 days 01:08:31.879000,1,0 days 00:01:39.862000,17,4,NaT,NaT,0 days 00:00:31.830000,0 days 00:00:42.657000,0 days 00:00:25.375000,...,284.0,MEDIUM,14.0,False,0 days 01:06:52.017000,Red Bull Racing,VER,1,True,2022-03-18 12:51:52.030
17,0 days 01:10:11.244000,1,0 days 00:01:39.365000,18,4,NaT,NaT,0 days 00:00:32.009000,0 days 00:00:42.772000,0 days 00:00:24.584000,...,282.0,MEDIUM,15.0,False,0 days 01:08:31.879000,Red Bull Racing,VER,1,True,2022-03-18 12:53:31.892
18,0 days 01:11:50.003000,1,0 days 00:01:38.759000,19,4,NaT,NaT,0 days 00:00:31.695000,0 days 00:00:42.627000,0 days 00:00:24.437000,...,283.0,MEDIUM,16.0,False,0 days 01:10:11.244000,Red Bull Racing,VER,1,True,2022-03-18 12:55:11.257
19,0 days 01:13:29.253000,1,0 days 00:01:39.250000,20,4,NaT,NaT,0 days 00:00:31.819000,0 days 00:00:42.776000,0 days 00:00:24.655000,...,282.0,MEDIUM,17.0,False,0 days 01:11:50.003000,Red Bull Racing,VER,1,True,2022-03-18 12:56:50.016
20,0 days 01:15:08.851000,1,0 days 00:01:39.598000,21,4,NaT,NaT,0 days 00:00:31.794000,0 days 00:00:43.095000,0 days 00:00:24.709000,...,287.0,MEDIUM,18.0,False,0 days 01:13:29.253000,Red Bull Racing,VER,1,True,2022-03-18 12:58:29.266
21,0 days 01:17:20.051000,1,0 days 00:02:11.200000,22,4,NaT,NaT,0 days 00:00:39.459000,0 days 00:00:52.633000,0 days 00:00:39.108000,...,233.0,MEDIUM,19.0,False,0 days 01:15:08.851000,Red Bull Racing,VER,1,True,2022-03-18 13:00:08.864
22,0 days 01:19:44.307000,1,0 days 00:02:24.256000,23,4,NaT,0 days 01:19:42.516000,0 days 00:01:05.784000,0 days 00:00:49.425000,0 days 00:00:29.047000,...,249.0,MEDIUM,20.0,False,0 days 01:17:20.051000,Red Bull Racing,VER,1,False,2022-03-18 13:02:20.064

In [38]:
fp1.car_data['1']

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2022-03-18 11:45:03.499,0,0,0,104,True,8,car,0 days 00:00:03.486000,0 days 00:00:03.486000
1,2022-03-18 11:45:03.739,0,0,0,104,True,8,car,0 days 00:00:03.726000,0 days 00:00:03.726000
2,2022-03-18 11:45:03.980,0,0,0,104,True,8,car,0 days 00:00:03.967000,0 days 00:00:03.967000
3,2022-03-18 11:45:04.140,0,0,0,104,True,8,car,0 days 00:00:04.127000,0 days 00:00:04.127000
4,2022-03-18 11:45:04.500,0,0,0,104,True,8,car,0 days 00:00:04.487000,0 days 00:00:04.487000
...,...,...,...,...,...,...,...,...,...,...
18355,2022-03-18 13:07:04.636,0,0,0,104,True,8,car,0 days 01:22:04.623000,0 days 01:22:04.623000
18356,2022-03-18 13:07:04.795,0,0,0,104,True,8,car,0 days 01:22:04.782000,0 days 01:22:04.782000
18357,2022-03-18 13:07:04.995,0,0,0,104,True,8,car,0 days 01:22:04.982000,0 days 01:22:04.982000
18358,2022-03-18 13:07:05.395,0,0,0,104,True,8,car,0 days 01:22:05.382000,0 days 01:22:05.382000
18359,2022-03-18 13:07:05.755,0,0,0,104,True,8,car,0 days 01:22:05.742000,0 days 01:22:05.742000

In [39]:
fp1.pos_data['1']

,Date,Status,X,Y,Z,Source,Time,SessionTime
0,2022-03-18 11:45:03.513,OnTrack,0,0,0,pos,0 days 00:00:03.500000,0 days 00:00:03.500000
1,2022-03-18 11:45:03.714,OnTrack,0,0,0,pos,0 days 00:00:03.701000,0 days 00:00:03.701000
2,2022-03-18 11:45:03.874,OnTrack,0,0,0,pos,0 days 00:00:03.861000,0 days 00:00:03.861000
3,2022-03-18 11:45:04.034,OnTrack,0,0,0,pos,0 days 00:00:04.021000,0 days 00:00:04.021000
4,2022-03-18 11:45:04.254,OnTrack,0,0,0,pos,0 days 00:00:04.241000,0 days 00:00:04.241000
...,...,...,...,...,...,...,...,...
18981,2022-03-18 13:07:04.553,OnTrack,-181,2330,-159,pos,0 days 01:22:04.540000,0 days 01:22:04.540000
18982,2022-03-18 13:07:04.873,OnTrack,-181,2330,-159,pos,0 days 01:22:04.860000,0 days 01:22:04.860000
18983,2022-03-18 13:07:05.233,OnTrack,-181,2330,-159,pos,0 days 01:22:05.220000,0 days 01:22:05.220000
18984,2022-03-18 13:07:05.613,OnTrack,-181,2330,-159,pos,0 days 01:22:05.600000,0 days 01:22:05.600000
18985,2022-03-18 13:07:05.793,OnTrack,-181,2330,-159,pos,0 days 01:22:05.780000,0 days 01:22:05.780000